### ISSUE TITLE
nelze editovat komentář k ssh klíčům

### ISSUE THREAD

**Issue by nesnera** [vpsfreecz/vpsadmin#13]
viz. snímek
![image](https://user-images.githubusercontent.com/1737463/96362871-d388ea80-1130-11eb-813e-8ef048ccf020.png)

**Comment by aither64** [comment]
Ten komentář se vytahuje z veřejného klíče, bývá úplně na konci oddělený mezerou. Změní se tedy upravením klíče. Na vlastní popisek tam máš "Label".
