### ISSUE TITLE
Error message: Resource allocation error: cannot allocate more ipv4 than is available (-1 left)

### ISSUE THREAD

**Issue by mmilata** [vpsfreecz/vpsadmin#15]
Seems like I've got -1 IPv4s left even though I only have 1 VPS (ID 15511) with one IPv4.

**Comment by aither64** [comment]
This belongs to vpsFree.cz support, not here, please write there next time.

You do have a second IPv4 assigned to your account, it's an adress from Brno. You can see it as the first address here https://vpsadmin.vpsfree.cz/?page=networking&action=ip_addresses&list=1&limit=25&offset=0&v=0&prefix=&vps=&network=0&location=0

I don't know how it came to be, if you don't need it we can free it.

**Comment by Kerrycek** [comment]
The IP address has been released
