### ISSUE TITLE
Možnost přihlášení s různou životností tokenu

### ISSUE THREAD

**Issue by rhsCZ** [vpsfreecz/vpsadmin#33]
Ahoj, chtělo by to při přihlášení aby si uživatel mohl zvolit životnost tokenu, aby kdyby nahodou zapoměl něco udělat, tak by se nemusel přihlašovat každých 20 minut. myslim, že by stačil dropbox s přednastavenými předvolbami např. 20 minut, 60 minut,2 hodiny, 4 hodiny, 8 hodin, 16 hodin, 24 hodin, 3 dny, permanentně

**Comment by aither64** [comment]
Je tam skrytá funkce prodloužení přihlášení: když klikneš na zbývající čas, prodlouží se to o 20 minut. Dlouhý klik pak odpočet zruší úplně. Platí to jen pro aktuální stránku v aktuálním tabu, při navigaci na jinou stránku tam skočí zase 20 min.

To co navrhuješ nevím jestli chceme dělat. Časový limit je tam schválně... asi by se dala vylepšit ta funkce co už tam je, ať si to tu změnu pamatuje.
