### ISSUE TITLE
"Create a new mount" in VPS admin fails

### ISSUE THREAD

**Issue by honza-klu** [vpsfreecz/vpsadmin#34]
I tried to create mountpoint for my dataset (#17502), but when I press "Create a new mount" link I get only blank page. Debugging it, I can see that there is 500 Internal Server Error.

![obrazek](https://user-images.githubusercontent.com/25118100/234302782-c58cb5a4-38db-4093-8a1e-67b9d3aac894.png)

**Comment by aither64** [comment]
It's a left-over link that should've been deleted. To mount a VPS dataset, click on "Mount" link in the "Datasets" form above. To mount NAS, see https://kb.vpsfree.cz/navody/vps/exporty

**Comment by aither64** [comment]
Link removed by d7a5812edbea507805924abd8d4a7649cedbf77e.
