### ISSUE TITLE
[Suggestion] Edit existing route gateway

### ISSUE THREAD

**Issue by rhsCZ** [vpsfreecz/vpsadmin#37]
Hi, it would be nice if we can edit existing routed ip/ranges to change if ip/range have gateway directly on network interface or via some IP address. This can be only specified when adding ip/range and can't be later edited without deleting and then adding route back.

**Comment by aither64** [comment]
I don't think this is worth investing time in. You set the routes up once and you're done. It's not like you're changing the routes afterwards when you have it configured to your liking... or I don't see the use-case.

**Comment by rhsCZ** [comment]
I think this will be useful mainly for testing purposes on playground for example. If i borrow for testing one /64 and one /48 ipv6 ranges where i cannot change routes(even by deleting and adding if i don't own these ipv6 ranges) if i want test something and i have to contact support for that, where i had to wait for response introducing delay to test something.
Decision is yours but i think it would be good.

**Comment by aither64** [comment]
I'm aware that the form for adding routes in VPS details is rather limited. I plan to replace it with something better, although I haven't yet decided how.
